[project]
name = "tool-registry"
version = "0.1.4-dev"
description = "Tools Registry (Catalogue of Tools): a reference implementation and specification to publish, curate, and expose valueâ€‘adding services, workflows, and tools in a managed registry."
readme = "README.md"
title = "Tool Registry API Service"
requires-python = ">=3.12.8"
dependencies = [
    "dynaconf>=3.2.12",
    "fastapi>=0.128.0",
]




