[default]

otlp_enable = false
log_file = "@format {env[BASE_DIR]}/logs/tlr.log"
log_level = 10
log_format = "%(asctime)s %(levelname)s %(name)s %(threadName)s : %(message)s"

supported_tools_dir = "@format {env[BASE_DIR]}/resources/supported-tools"