[logging]
log_file = "@format {env[BASE_DIR]}/logs/tool-registry.log"
log_level = "DEBUG"
use_detailed_format = false

[database]
host = "localhost"
port = 5432
name = "admin"
user = "harvester"
password = ""

[oxigraph]
host = "localhost"
port = 7878
namespace = "http://eosc-data-commons.eu/graph/tools"
user = ""
password = ""


[service]
name = "Tool Registry"
listen_port = 8181
bind_address = "127.0.0.1"
api_prefix = "/api/v1"
admin_auth_key = "changeme"
